services:
  - type: web
    name: new-site-making
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: EXAMPLE_KEY
        sync: false
